#!/bin/sh

set -e

CPUS=$(getconf _NPROCESSORS_ONLN)
case "$CPUS" in
  [0-9]|[0-9][0-9]|[0-9][0-9][0-9]) ;;
  *) CPUS=1
esac

set -x
DEB_BUILD_OPTIONS="parallel=$CPUS nohppa nomult nocross" dpkg-buildpackage -d -B --no-sign
